description: "Builds the id-checker project for Debian GNU/Linux family"
name: "Build for Debian GNU/Linux family"
outputs:
  out-path:
    description: "Output file path"
    value: "${{ steps.build.outputs.out-path }}"
  version:
    description: "App version"
    value: "${{ steps.version.outputs.value }}"
runs:
  steps:
    - env:
        GPG_PRIVATE_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
        GPG_PRIVATE_KEY_PASSPHRASE: "${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}"
      name: "Import GPG key"
      shell: "bash"
      run: |
        gpg \
          --batch \
          --import \
          --no-tty \
          --passphrase-fd 3 \
          --pinentry-mode loopback \
          --yes \
          <<<"$GPG_PRIVATE_KEY" \
          3<<<"$GPG_PRIVATE_KEY_PASSPHRASE"
    - name: "Install Tauri dependencies"
      shell: "bash"
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends --no-install-suggests \
          dpkg-sig \
          libappindicator3-dev \
          libgtk-3-dev \
          librsvg2-dev \
          libwebkit2gtk-4.1-dev
    - name: "Install pnpm"
      uses: "pnpm/action-setup@v6"
    - name: "Setup Node.js"
      uses: "actions/setup-node@v6"
      with:
        cache: "pnpm"
        node-version: 26
    - name: "Setup latest Rust toolchain"
      uses: "dtolnay/rust-toolchain@nightly"
      with:
        targets: "x86_64-unknown-linux-gnu"
    - name: "Install frontend dependencies"
      shell: "bash"
      run: "pnpm ci"
    - name: "Install backend dependencies"
      shell: "bash"
      run: "cargo fetch"
    - id: "product-name"
      name: "Get product name"
      uses: "SebRollen/toml-action@v1.2.0"
      with:
        field: "productName"
        file: "src-tauri/Tauri.toml"
    - id: "version"
      name: "Get version"
      uses: "SebRollen/toml-action@v1.2.0"
      with:
        field: "package.version"
        file: "src-tauri/Cargo.toml"
    - env:
        GPG_SIGN_KEY: "${{ vars.GPG_SIGN_KEY }}"
      id: "build"
      name: "Build"
      shell: "bash"
      run: |
        pnpm tauri build -b deb
        dir=$PWD/target/release/bundle/deb
        name="${{ steps.product-name.outputs.value }}"
        ver="${{ steps.version.outputs.value }}"
        fullname=${name}_${ver}_amd64
        if [[ ! -f $dir/$fullname.deb ]]; then
          file=$(find "$dir" -type f -name '*.deb')
          printf "\e[1;31mError: installer file name is wrong\e[m\n"
          printf "  expected: \e[33m%s/%s.deb\e[m\n" "$dir" "$fullname"
          printf "  found: \e[33m%s\e[m\n" "$file"
          exit 1
        fi
        dpkg-sig --sign builder -k "$GPG_SIGN_KEY" "$dir/$fullname.deb"
        mkdir out
        mv "$dir/$fullname.deb" "$GITHUB_WORKSPACE/out/$fullname.deb"
        echo "out-path=./out/$fullname.deb" >>"$GITHUB_OUTPUT"
  using: "composite"
