description: "Builds the id-checker project for macOS (Universal)"
inputs:
  token:
    description: "GitHub Token (unused)"
    required: false
name: "Build for macOS"
outputs:
  out-path:
    description: "Output file path"
    value: "${{ steps.build.outputs.out-path }}"
  version:
    description: "App version"
    value: "${{ steps.version.outputs.value }}"
runs:
  steps:
    - name: "Install pnpm"
      uses: "pnpm/action-setup@v6"
    - name: "Setup Node.js"
      uses: "actions/setup-node@v6"
      with:
        cache: "pnpm"
        node-version: 26
    - name: "Setup latest Rust toolchain"
      uses: "dtolnay/rust-toolchain@nightly"
      with:
        targets: "aarch64-apple-darwin,x86_64-apple-darwin"
    - name: "Install frontend dependencies"
      shell: "bash"
      run: "pnpm ci"
    - name: "Install backend dependencies"
      shell: "bash"
      run: "cargo fetch"
    - id: "product-name"
      name: "Get product name"
      uses: "SebRollen/toml-action@v1.2.0"
      with:
        field: "productName"
        file: "src-tauri/Tauri.toml"
    - id: "version"
      name: "Get version"
      uses: "SebRollen/toml-action@v1.2.0"
      with:
        field: "package.version"
        file: "src-tauri/Cargo.toml"
    - id: "build"
      name: "Build"
      shell: "bash"
      run: |
        pnpm tauri build --target universal-apple-darwin
        dir=$PWD/target/release/bundle/dmg
        name="${{ steps.product-name.outputs.value }}"
        ver="${{ steps.version.outputs.value }}"
        fullname=${name}_${ver}_universal
        if [[ ! -f $dir/$fullname.dmg ]]; then
          printf "\e[1;31mError: installer file name is wrong\e[m\n"
          printf "  expected: \e[33m$dir/$fullname.dmg\e[m\n"
          printf "  found: \e[33m$dir/"*".dmg\e[m\n"
          exit 1
        fi
        mkdir out
        mv "$dir/$fullname.dmg" "$GITHUB_WORKSPACE/out/$fullname.dmg"
        echo "out-path=./out/$fullname.dmg" >>"$GITHUB_OUTPUT"
  using: "composite"
