description: "Builds the id-checker project for ArchLinux"
inputs:
  gpg-private-key:
    description: "GPG private key for signing"
    required: true
  gpg-private-key-passphrase:
    description: "Passphrase of GPG private key for signing"
    required: true
  gpg-sign-key:
    description: "GPG key id for signing"
    required: true
  gpg-sign-key-keygrip:
    description: "Keygrip of GPG key for signing"
    required: true
name: "Build for ArchLinux"
outputs:
  version:
    description: "App version"
runs:
  image: "Dockerfile"
  using: "docker"
